/**
 * @file access_flags.hpp
 * @brief Access flags for class files, fields, and methods.
 *
 * Mirrors the access flag bitmasks defined in the JVM Specification
 * §4.1 (Class), §4.5 (Field), and §4.6 (Method).
 *
 */
#pragma once

#include "types.hpp"

namespace jvm {

namespace flags {

// --- Class Access Flags (JVM Spec §4.1, Table 4.1-A) ---
/// @brief Class-level access and property modifiers.
enum class Class : U2 {
  PUBLIC     = 0x0001,  ///< Declared public; accessible from outside its package.
  FINAL      = 0x0010,  ///< Declared final; no subclasses allowed.
  SUPER      = 0x0020,  ///< Treat superclass methods specially via invokespecial.
  INTERFACE  = 0x0200,  ///< Is an interface, not a class.
  ABSTRACT   = 0x0400,  ///< Declared abstract; must not be instantiated.
  SYNTHETIC  = 0x1000,  ///< Not present in source code; compiler-generated.
  ANNOTATION = 0x2000,  ///< Declared as an annotation type.
  ENUM       = 0x4000,  ///< Declared as an enum type.
};

// --- Method Access Flags (JVM Spec §4.6, Table 4.6-A) ---
/// @brief Method-level access and property modifiers.
enum class Method : U2 {
  PUBLIC       = 0x0001,  ///< Accessible from any class.
  PRIVATE      = 0x0002,  ///< Accessible only within the defining class.
  PROTECTED    = 0x0004,  ///< Accessible within package and subclasses.
  STATIC       = 0x0008,  ///< Class method (as opposed to instance method).
  FINAL        = 0x0010,  ///< Cannot be overridden.
  SYNCHRONIZED = 0x0020,  ///< Method is synchronized; monitor entry on invocation.
  BRIDGE       = 0x0040,  ///< Bridge method, generated by the compiler.
  VARARGS      = 0x0080,  ///< Method accepts variable number of arguments.
  NATIVE       = 0x0100,  ///< Implemented in a language other than Java.
  ABSTRACT     = 0x0400,  ///< No implementation is provided.
  STRICT       = 0x0800,  ///< Strict floating-point mode (FP-strict).
  SYNTHETIC    = 0x1000,  ///< Compiler-generated; not present in source.
};

// --- Field Access Flags (JVM Spec §4.5, Table 4.5-A) ---
/// @brief Field-level access and property modifiers.
enum class Field : U2 {
  PUBLIC    = 0x0001,  ///< Accessible from any class.
  PRIVATE   = 0x0002,  ///< Accessible only within the defining class.
  PROTECTED = 0x0004,  ///< Accessible within package and subclasses.
  STATIC    = 0x0008,  ///< Class field (as opposed to instance field).
  FINAL     = 0x0010,  ///< Cannot be modified after initialization.
  VOLATILE  = 0x0040,  ///< Field is volatile; accesses must use memory barrier.
  TRANSIENT = 0x0080,  ///< Not serialized during default serialization.
  SYNTHETIC = 0x1000,  ///< Compiler-generated; not present in source.
  ENUM      = 0x4000,  ///< Declared as an element of an enum type.
};
}  // namespace flags

/// @brief Generic access flag checker template parameterized by flag enum type.
///
/// Allows runtime querying of class, method, and field access flags.
///
/// @tparam FlagEnum The enum class type (one of flags::Class, flags::Method, flags::Field).
template <typename FlagEnum>
class AccessFlags {
 public:
  /// Construct with all flags cleared.
  AccessFlags() : flags_(0) {}

  /// Construct from a raw U2 bitmask.
  explicit AccessFlags(U2 flags) : flags_(flags) {}

  /// @brief Check whether a specific flag is set.
  /// @param flag The flag to test.
  /// @return true if the flag bit is set in the bitmask.
  bool has(FlagEnum flag) const { return (flags_ & static_cast<U2>(flag)) != 0; }

  /// @brief Return the raw U2 bitmask.
  U2 getFlags() const { return flags_; }

 private:
  U2 flags_;  ///< Raw bitmask of access flags.
};

}  // namespace jvm